In [0]:
#multiple linear regression
#import the libraaries

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [10]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [0]:
#location of database
dataset = pd.read_csv('/content/gdrive/My Drive/future/multiple_linear_regression/50_companies.csv')

In [0]:
#split the data into depenent and independent variable
X= dataset.iloc[:,:-1].values
Y=dataset.iloc[:,4].values


In [13]:
print(X)

[[185849.2 151897.8 492284.1 'Bangalore']
 [183097.7 166377.59 464398.53 'Hyderabad']
 [173941.51 116145.55 428434.54 'Pune']
 [164872.41 133671.85 403699.62 'Bangalore']
 [162607.34 106391.77 386668.42 'Pune']
 [152376.9 114814.71 383361.36 'Bangalore']
 [155115.46 162198.87 148216.82 'Hyderabad']
 [150798.13 160530.06 344376.68 'Pune']
 [141042.52 163718.95 332113.29 'Bangalore']
 [143834.88 123679.17 325481.62 'Hyderabad']
 [122413.08 125594.11 249660.95 'Pune']
 [121171.96 106790.61 270244.55 'Hyderabad']
 [114363.75 142320.38 270339.44 'Pune']
 [112492.39 150495.07 273164.93 'Hyderabad']
 [140443.24 171547.42 277012.92 'Pune']
 [135023.61 137616.84 282276.23 'Bangalore']
 [98513.11 136597.55 284846.06 'Hyderabad']
 [115157.16 160077.58 303074.31 'Bangalore']
 [112249.16 129175.79 315419.57 'Pune']
 [106919.7 168514.11 20500.0 'Bangalore']
 [96753.86 128867.3 319164.47 'Hyderabad']
 [98889.47 168773.43 320237.29 'Bangalore']
 [94494.56 137782.75 323819.26 'Pune']
 [88032.53 120751.

In [23]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
labelencoder = LabelEncoder()
X[:, 3] = labelencoder.fit_transform(X[:, 3])
print(X)
#onehotencoder = OneHotEncoder(categories= 'auto' )
#onehotencoder = OneHotEncoder(categorical_features = [3])
#X = onehotencoder.fit_transform(X).toarray()

ct = ColumnTransformer([("Location", OneHotEncoder(), [3])], remainder = 'passthrough')
X = ct.fit_transform(X)

print(X)

[[185849.2 151897.8 492284.1 0]
 [183097.7 166377.59 464398.53 1]
 [173941.51 116145.55 428434.54 2]
 [164872.41 133671.85 403699.62 0]
 [162607.34 106391.77 386668.42 2]
 [152376.9 114814.71 383361.36 0]
 [155115.46 162198.87 148216.82 1]
 [150798.13 160530.06 344376.68 2]
 [141042.52 163718.95 332113.29 0]
 [143834.88 123679.17 325481.62 1]
 [122413.08 125594.11 249660.95 2]
 [121171.96 106790.61 270244.55 1]
 [114363.75 142320.38 270339.44 2]
 [112492.39 150495.07 273164.93 1]
 [140443.24 171547.42 277012.92 2]
 [135023.61 137616.84 282276.23 0]
 [98513.11 136597.55 284846.06 1]
 [115157.16 160077.58 303074.31 0]
 [112249.16 129175.79 315419.57 2]
 [106919.7 168514.11 20500.0 0]
 [96753.86 128867.3 319164.47 1]
 [98889.47 168773.43 320237.29 0]
 [94494.56 137782.75 323819.26 2]
 [88032.53 120751.03 325268.73 2]
 [97544.01 114281.34 161074.81 0]
 [85164.71 154553.16 158462.62 1]
 [95828.87 159135.98 154550.07 2]
 [92607.6 142864.55 373683.81 0]
 [86551.52 197645.56 138648.2 2]
 [8610

In [26]:
# Avoiding the Dummy Variable Trap
#X = X[:, 1:]
#print(X)
#splitting the dataset as training and testing dataset
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size = 0.2, random_state=0)


# Fitting Multiple Linear Regression to the Training set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, Y_train)

# Predicting the Test set results
y_pred = regressor.predict(X_test)
#Actual Value 
print(Y_test)
#Prediced Value
print(y_pred)

[128282.38 169259.4  171121.95 102798.83 216050.39 130008.31 106229.06
 122483.56 135352.25 191187.94]
[128015.20159797 157582.27760813 157447.73845173  96976.0985126
 203537.48221051 141161.24230166  92851.69209679 123791.73374689
 138969.43533012 192921.06569547]
